import { DiagnosticProgram } from '@/types/program';

export const DIAGNOSTIC_PROGRAMS: DiagnosticProgram[] = [
  {
    id: 'prog-cgx',
    slug: 'cancer-genetics',
    name: 'Hereditary Cancer Risk Screening (CGx)',
    clinicalCode: 'PANEL-CGX-32',
    category: 'oncology',
    heroBadge: 'Hereditary Cancer Risk • Comprehensive 32-Gene Panel',
    shortDescription: 'Comprehensive genomic analysis assessing hereditary predisposition to breast, ovarian, colorectal, prostate, pancreatic, and gastric cancers.',
    fullOverview: 'The Hereditary Cancer Screening Panel evaluates high-penetrance and moderate-risk genetic variants associated with inherited cancer syndromes. By analyzing 30+ critical tumor-suppressor genes and DNA mismatch repair pathways, this panel enables proactive surveillance, early-stage detection, and personalized prophylactic strategies for patients and their families.',
    iconName: 'ShieldAlert',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'BRCA1 / BRCA2',
        name: 'Breast Cancer Type 1 & 2 Susceptibility',
        clinicalSignificance: 'High-penetrance variants linked to hereditary breast, ovarian, prostate, and pancreatic cancer.',
        actionableImpact: 'Informs enhanced mammography/MRI schedules, early PSA screening, and targeted PARP inhibitor therapy suitability.',
      },
      {
        symbol: 'MLH1, MSH2, MSH6, PMS2',
        name: 'DNA Mismatch Repair Lynch Syndrome Panel',
        clinicalSignificance: 'Associated with elevated risk of colorectal, endometrial, ovarian, and gastrointestinal malignancies.',
        actionableImpact: 'Guides accelerated colonoscopy frequency (every 1–2 years) starting at earlier clinical ages.',
      },
      {
        symbol: 'TP53 & PTEN',
        name: 'Li-Fraumeni & Cowden Syndrome Regulators',
        clinicalSignificance: 'Critical tumor suppressor genes governing cellular apoptosis and cell-cycle checkpoint control.',
        actionableImpact: 'Directs whole-body MRI protocols and proactive multi-organ clinical surveillance.',
      },
      {
        symbol: 'PALB2 & CHEK2',
        name: 'Partner and Localizer of BRCA2 / Checkpoint Kinase 2',
        clinicalSignificance: 'Moderate-to-high risk modifiers for breast, prostate, and digestive tract neoplasms.',
        actionableImpact: 'Supports personalized clinical risk stratification when multi-generational family history is present.',
      },
    ],
    clinicalIndications: [
      'Personal diagnosis of breast, ovarian, colorectal, or pancreatic cancer at any age.',
      'Two or more close blood relatives (parents, siblings, children) diagnosed with cancer.',
      'Family member diagnosed with a known hereditary pathogenic gene mutation (e.g., BRCA1/2).',
      'Male breast cancer in family lineage.',
      'Early-onset cancer diagnosis in immediate family members (<50 years of age).',
      'Multiple primary cancers diagnosed in the same individual.',
    ],
    medicareCoverageCriteria: 'Physician-ordered hereditary cancer screening evaluates high-penetrance mutations across 30+ critical tumor-suppressor genes. Processed in CAP/CLIA-accredited laboratories to deliver clear, actionable surveillance protocols for patients and their clinical providers.',
    sampleReportSummary: {
      resultStatus: 'Pathogenic Variant Identified',
      keyFinding: 'Pathogenic heterozygous variant identified in BRCA2 (c.5946delT, p.Ser1982fs).',
      clinicalRecommendation: 'Recommend referral to genetic counselor, enhanced annual breast MRI alternating with mammography, and early prostate/pancreatic screening discussion with PCP.',
    },
    keyStats: [
      { label: 'Genes Evaluated', value: '32 Genes' },
      { label: 'Analytical Accuracy', value: '99.9%' },
      { label: 'Turnaround Time', value: '7–10 Days' },
      { label: 'Specimen Collection', value: '5-Min Swab' },
    ],
  },
  {
    id: 'prog-pgx',
    slug: 'pharmacogenomics',
    name: 'Pharmacogenomics Drug-Gene Response (PGx)',
    clinicalCode: 'PANEL-PGX-18',
    category: 'pharmacology',
    heroBadge: 'Precision Medication • Avoid Adverse Drug Events',
    shortDescription: 'Analyzes liver enzyme genetics to predict how your body metabolizes cardiology, psychotropic, pain, and gastrointestinal medications.',
    fullOverview: 'Pharmacogenomic (PGx) testing unlocks how individual genetic variations impact drug metabolism, efficacy, and adverse reaction risks. By sequencing cytochrome P450 enzymes and drug transporters, providers can replace trial-and-error prescribing with precision pharmacology—optimizing dosages and preventing dangerous drug-drug and drug-gene toxicities.',
    iconName: 'Pill',
    sampleTurnaround: '5–7 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'CYP2D6',
        name: 'Cytochrome P450 Family 2 Subfamily D Member 6',
        clinicalSignificance: 'Metabolizes ~25% of all common prescription drugs, including beta-blockers, antiarrhythmics, SSRIs, and opioids.',
        actionableImpact: 'Identifies Poor, Intermediate, Normal, or Ultrarapid metabolizers to guide precise dosing and avoid toxicity or therapeutic failure.',
      },
      {
        symbol: 'CYP2C19',
        name: 'Cytochrome P450 Family 2 Subfamily C Member 19',
        clinicalSignificance: 'Critical for activation of antiplatelet agents (clopidogrel/Plavix), proton pump inhibitors, and antidepressants.',
        actionableImpact: 'Prevents post-stent cardiac complications by identifying clopidogrel resistance and guiding alternative antiplatelet therapies.',
      },
      {
        symbol: 'CYP2C9 & VKORC1',
        name: 'Warfarin & Statin Sensitivity Enzymes',
        clinicalSignificance: 'Regulates anticoagulant clearance (Coumadin) and statin-induced myopathy risk.',
        actionableImpact: 'Guides initial therapeutic warfarin dosing windows to avoid dangerous hemorrhagic or clotting events.',
      },
      {
        symbol: 'SLCO1B1',
        name: 'Solute Carrier Organic Anion Transporter Family 1B1',
        clinicalSignificance: 'Controls hepatic uptake of HMG-CoA reductase inhibitors (simvastatin, atorvastatin).',
        actionableImpact: 'Eliminates severe muscle pain (myopathy/rhabdomyolysis) by selecting well-tolerated statin alternatives.',
      },
    ],
    clinicalIndications: [
      'Currently taking 3 or more daily prescription medications (Polypharmacy).',
      'History of unexpected side effects, nausea, dizziness, or adverse reactions to medications.',
      'Taking blood thinners (Warfarin, Plavix/Clopidogrel) or cardiovascular therapies.',
      'Suboptimal response to antidepressant, anti-anxiety, or neurological drugs.',
      'Chronic pain management requiring opioid or NSAID dose adjustments.',
      'Starting a new critical prescription regimen where precise therapeutic dosing is vital.',
    ],
    medicareCoverageCriteria: 'Physician-ordered pharmacogenomic profiling assesses liver enzyme pathways to optimize medication effectiveness and prevent adverse drug interactions across 250+ commonly prescribed medications.',
    sampleReportSummary: {
      resultStatus: 'Moderate Risk Factor',
      keyFinding: 'CYP2C19 Intermediate Metabolizer (*1/*2) and SLCO1B1 Decreased Function (*5 allele).',
      clinicalRecommendation: 'Consider alternative antiplatelet therapy to clopidogrel (e.g. ticagrelor/Prasugrel) and adjust simvastatin dosage to prevent statin-related myopathy.',
    },
    keyStats: [
      { label: 'Medications Profiled', value: '250+ Drugs' },
      { label: 'Enzymes Tested', value: '18 Biomarkers' },
      { label: 'Turnaround Time', value: '5–7 Days' },
      { label: 'Collection Method', value: 'Buccal Swab' },
    ],
  },
  {
    id: 'prog-neuro',
    slug: 'neurocognitive',
    name: 'Neurocognitive & Dementia Genetics Panel',
    clinicalCode: 'PANEL-NCG-14',
    category: 'neurology',
    heroBadge: 'Proactive Brain Health • Early Intervention',
    shortDescription: 'Evaluates genetic risk factors and biomarkers associated with age-related cognitive decline, Alzheimer’s disease, and memory disorders.',
    fullOverview: 'The Neurocognitive and Neurological Panel analyzes established genetic markers linked to late-onset memory impairment, cerebral amyloid deposition, and neurodegenerative conditions. Early identification allows healthcare providers to implement evidence-based neuroprotective interventions, vascular health monitoring, and personalized cognitive wellness plans years before clinical symptoms progress.',
    iconName: 'Brain',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'APOE (e2 / e3 / e4 alleles)',
        name: 'Apolipoprotein E Allelic Genotyping',
        clinicalSignificance: 'The strongest established genetic susceptibility marker for late-onset sporadic cognitive decline.',
        actionableImpact: 'Informs early lifestyle, vascular risk management, sleep hygiene, and specialized neurological baseline testing.',
      },
      {
        symbol: 'PSEN1 & PSEN2',
        name: 'Presenilin 1 & 2 Catalytic Subunits',
        clinicalSignificance: 'Regulates amyloid precursor protein (APP) processing and gamma-secretase activity.',
        actionableImpact: 'Distinguishes early-onset familial variants from age-related memory vulnerabilities.',
      },
      {
        symbol: 'MAPT & GRN',
        name: 'Microtubule-Associated Protein Tau & Progranulin',
        clinicalSignificance: 'Associated with frontotemporal lobar degeneration and tauopathy pathways.',
        actionableImpact: 'Assists clinicians in differential diagnosis of atypical neurological and movement symptoms.',
      },
    ],
    clinicalIndications: [
      'Personal concerns regarding memory lapses, brain fog, or cognitive slowdown.',
      'Immediate family member diagnosed with Alzheimer’s, vascular dementia, or Parkinson’s disease.',
      'Co-occurring cardiovascular risk factors (hypertension, high homocysteine) impacting cerebral blood flow.',
      'Patients over 65 seeking baseline neurocognitive risk assessments.',
    ],
    medicareCoverageCriteria: 'Physician-ordered neurocognitive genomic screening evaluates APOE allelic genotypes and key risk biomarkers to empower proactive cognitive health, lifestyle interventions, and personalized neurological surveillance.',
    sampleReportSummary: {
      resultStatus: 'Moderate Risk Factor',
      keyFinding: 'APOE Genotype: e3/e4 (Heterozygous for the e4 susceptibility allele).',
      clinicalRecommendation: 'Recommend annual Montreal Cognitive Assessment (MoCA), intensive management of cardiovascular lipids/blood pressure, and antioxidant-rich Mediterranean dietary protocol.',
    },
    keyStats: [
      { label: 'Key Markers Tested', value: 'APOE & 12 Genes' },
      { label: 'Clinical Accuracy', value: '99.9%' },
      { label: 'Medicare Coverage', value: 'Part B Eligible' },
      { label: 'At-Home Process', value: '100% Painless' },
    ],
  },
  {
    id: 'prog-immune',
    slug: 'immunodeficiency',
    name: 'Primary Immunodeficiency & Autoimmune Health',
    clinicalCode: 'PANEL-PID-24',
    category: 'immunology',
    heroBadge: 'Immune Defense • Recurrent Infection Analysis',
    shortDescription: 'Uncovers inherited immune system defects that cause chronic infections, poor antibiotic response, and severe autoimmune conditions.',
    fullOverview: 'Primary Immunodeficiency Disorders (PIDDs) frequently go undiagnosed in adults, masquerading as routine recurrent sinus, ear, or bronchial infections. This panel sequences genes governing antibody synthesis, T-cell regulation, and complement pathways, providing physicians with definitive answers to resolve lifelong immune vulnerabilities.',
    iconName: 'Activity',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'BTK',
        name: 'Bruton Tyrosine Kinase',
        clinicalSignificance: 'Essential for B-cell maturation and immunoglobulin synthesis.',
        actionableImpact: 'Enables targeted immunoglobulin replacement therapy (IVIG/SCIG) to halt recurring bacterial infections.',
      },
      {
        symbol: 'STAT1 & STAT3',
        name: 'Signal Transducer and Activator of Transcription',
        clinicalSignificance: 'Regulates interferon responses and mucosal barrier immunity against fungal and viral pathogens.',
        actionableImpact: 'Guides precise antimicrobial prophylaxis and biological immunomodulatory therapies.',
      },
      {
        symbol: 'NFKB1 & CTLA4',
        name: 'Immune Checkpoint and Nuclear Factor Regulators',
        clinicalSignificance: 'Governs immune tolerance and limits systemic autoimmune hyperactivation.',
        actionableImpact: 'Informs therapeutic decisions for combined immunodeficiency with autoimmune enteropathy or cytopenias.',
      },
    ],
    clinicalIndications: [
      'Four or more new ear infections within one year, or two or more serious sinus infections within one year.',
      'Two or more episodes of pneumonia within a three-year period.',
      'Need for intravenous antibiotics to clear recurring bacterial infections.',
      'Persistent unexplained low white blood cell or immunoglobulin levels.',
      'Co-occurrence of multiple autoimmune conditions (e.g., lupus, rheumatoid arthritis, thyroiditis).',
    ],
    medicareCoverageCriteria: 'Physician-ordered immunodeficiency testing sequences 24 critical immune defense genes to diagnose underlying antibody deficiencies, recurrent infection susceptibility, and autoimmune risks.',
    sampleReportSummary: {
      resultStatus: 'Pathogenic Variant Identified',
      keyFinding: 'Variant of Clinical Significance identified in NFKB1 (p.Arg157Ter).',
      clinicalRecommendation: 'Recommend quantitative immunoglobulin profiling (IgG, IgA, IgM), clinical immunologist referral, and evaluation for prophylactic antibiotic protocols.',
    },
    keyStats: [
      { label: 'Immune Genes', value: '24 Targets' },
      { label: 'Collection Time', value: '5 Minutes' },
      { label: 'Turnaround Time', value: '7–10 Days' },
      { label: 'Lab Certification', value: 'CLIA & CAP' },
    ],
  },
  {
    id: 'prog-cardio',
    slug: 'cardiovascular',
    name: 'Cardiovascular & Cardiometabolic Panel',
    clinicalCode: 'PANEL-CVD-28',
    category: 'cardiovascular',
    heroBadge: 'Early Heart Protection • Inherited Lipid Risk',
    shortDescription: 'Identifies inherited mutations driving premature heart attack, familial high cholesterol, cardiomyopathies, and sudden cardiac risk.',
    fullOverview: 'Over 50% of premature cardiovascular events have an underlying hereditary component. This panel examines genes linked to Familial Hypercholesterolemia (FH), hypertrophic and dilated cardiomyopathies, thoracic aortic aneurysms, and cardiac channelopathies—giving your physician the clinical data necessary to protect your cardiovascular health proactively.',
    iconName: 'HeartPulse',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'LDLR, APOB, PCSK9',
        name: 'Familial Hypercholesterolemia Clearance Trio',
        clinicalSignificance: 'Regulates LDL cholesterol uptake and lifelong arterial plaque accumulation rates.',
        actionableImpact: 'Qualifies patients for high-potency statins or advanced PCSK9 inhibitor therapies to dramatically lower cardiac event risks.',
      },
      {
        symbol: 'MYH7 & MYBPC3',
        name: 'Cardiac Sarcomere Structural Proteins',
        clinicalSignificance: 'Primary genetic drivers of hypertrophic and dilated cardiomyopathy.',
        actionableImpact: 'Directs regular echocardiograms, Holter monitoring, and personalized exercise/exertion safety boundaries.',
      },
      {
        symbol: 'KCNQ1 & SCN5A',
        name: 'Cardiac Ion Channel Conductors',
        clinicalSignificance: 'Linked to Long QT Syndrome, Brugada syndrome, and familial arrhythmia predispositions.',
        actionableImpact: 'Prevents sudden cardiac events by avoiding contraindicated QT-prolonging medications and guiding beta-blocker therapy.',
      },
    ],
    clinicalIndications: [
      'Immediate family member suffered a heart attack or stroke before age 55 (men) or 65 (women).',
      'Persistent LDL cholesterol > 190 mg/dL unresponsive to standard lifestyle changes.',
      'Personal diagnosis or family history of unexplained cardiac arrhythmia, syncope (fainting), or cardiomyopathy.',
      'Family history of aortic aneurysm or sudden unexplained cardiac death in young relatives.',
    ],
    medicareCoverageCriteria: 'Physician-ordered cardiovascular genomic analysis evaluates 28 cardiac biomarkers to identify inherited risks for familial hypercholesterolemia, cardiomyopathies, and early-onset vascular events.',
    sampleReportSummary: {
      resultStatus: 'Pathogenic Variant Identified',
      keyFinding: 'Pathogenic variant detected in LDLR (c.1775G>A, p.Gly592Glu) consistent with Familial Hypercholesterolemia.',
      clinicalRecommendation: 'Recommend intensive lipid-lowering therapy, baseline coronary artery calcium (CAC) scan, and cascade screening for first-degree family members.',
    },
    keyStats: [
      { label: 'Cardio Genes', value: '28 Targets' },
      { label: 'Accuracy', value: '99.9%' },
      { label: 'Turnaround Time', value: '7–10 Days' },
      { label: 'Method', value: 'Cheek Swab' },
    ],
  },
  {
    id: 'prog-pulmonary',
    slug: 'pulmonary',
    name: 'Pulmonary & Respiratory Genetics Panel',
    clinicalCode: 'PANEL-PUL-12',
    category: 'pulmonary',
    heroBadge: 'Alpha-1 Screening • Chronic Lung Protection',
    shortDescription: 'Detects inherited vulnerabilities for COPD, early-onset emphysema, adult asthma, and Alpha-1 Antitrypsin Deficiency.',
    fullOverview: 'Chronic lung disease is not always caused by environmental factors or smoking. Genetic conditions like Alpha-1 Antitrypsin Deficiency (AATD) predispose individuals to accelerated lung tissue breakdown and liver impairment. This panel delivers rapid genomic confirmation to enable lung-sparing lifestyle adjustments and targeted augmentation therapy.',
    iconName: 'Wind',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'SERPINA1',
        name: 'Alpha-1 Antitrypsin Protease Inhibitor',
        clinicalSignificance: 'The definitive gene for Alpha-1 Antitrypsin Deficiency (PI*S, PI*Z, and null alleles).',
        actionableImpact: 'Qualifies eligible patients for enzyme augmentation therapy and rigorous pulmonary function surveillance.',
      },
      {
        symbol: 'CFTR',
        name: 'Cystic Fibrosis Transmembrane Conductance Regulator',
        clinicalSignificance: 'Assesses atypical adult bronchiectasis, recurrent bronchitis, and mild CFTR-related respiratory disorders.',
        actionableImpact: 'Informs specialized airway clearance techniques, nebulizer protocols, and targeted CFTR modulators.',
      },
      {
        symbol: 'SFTPC & ABCA3',
        name: 'Surfactant Metabolism and Alveolar Integrity',
        clinicalSignificance: 'Linked to familial idiopathic pulmonary fibrosis (IPF) and interstitial lung diseases.',
        actionableImpact: 'Supports early high-resolution chest CT monitoring and antifibrotic medication timing.',
      },
    ],
    clinicalIndications: [
      'Diagnosis of COPD or emphysema at an unusually early age (<50 years).',
      'COPD or chronic shortness of breath with little or no smoking history.',
      'Unexplained chronic cough, wheezing, or frequent respiratory infections.',
      'Immediate family member diagnosed with Alpha-1 Antitrypsin Deficiency.',
      'Unexplained bronchiectasis or familial interstitial lung disease.',
    ],
    medicareCoverageCriteria: 'Physician-ordered respiratory genomic testing identifies hereditary Alpha-1 Antitrypsin mutations and surfactant gene variations to protect lung function and support early pulmonary management.',
    sampleReportSummary: {
      resultStatus: 'Pathogenic Variant Identified',
      keyFinding: 'SERPINA1 Genotype: PI*MZ (Carrier of the severe Z deficiency allele with moderate serum reduction).',
      clinicalRecommendation: 'Recommend baseline spirometry, avoidance of all aerosol irritants, and prompt medical treatment for lower respiratory infections.',
    },
    keyStats: [
      { label: 'Pulmonary Genes', value: '12 Targets' },
      { label: 'Turnaround Time', value: '7–10 Days' },
      { label: 'Lab Process', value: 'NGS Certified' },
      { label: 'At-Home Kit', value: 'Free USPS 2-Way' },
    ],
  },
  {
    id: 'prog-metabolic',
    slug: 'metabolic-diabetes',
    name: 'Metabolic & Monogenic Diabetes Panel',
    clinicalCode: 'PANEL-MET-16',
    category: 'metabolic',
    heroBadge: 'Monogenic Diabetes • Precision Endocrine Care',
    shortDescription: 'Distinguishes inherited monogenic diabetes (MODY) from typical Type 2 diabetes to optimize treatment without unnecessary insulin.',
    fullOverview: 'Up to 5% of patients diagnosed with Type 2 diabetes actually have Monogenic Diabetes (MODY), an inherited single-gene disorder. Correct genetic classification can allow patients to transition from daily insulin injections to simple, well-tolerated oral sulfonylurea tablets, dramatically improving blood sugar control and quality of life.',
    iconName: 'Flame',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'HNF1A & HNF4A',
        name: 'Hepatocyte Nuclear Factor 1 & 4 Alpha (MODY 3 & 1)',
        clinicalSignificance: 'Regulates pancreatic beta-cell insulin secretion response to glucose.',
        actionableImpact: 'Allows clinical transition from insulin to low-dose oral sulfonylureas with superior glycemic control.',
      },
      {
        symbol: 'GCK',
        name: 'Glucokinase Pancreatic Glucose Sensor (MODY 2)',
        clinicalSignificance: 'Controls the baseline fasting glucose threshold in liver and pancreas.',
        actionableImpact: 'Confirms benign, stable mild hyperglycemia that typically requires zero medication, avoiding overtreatment.',
      },
      {
        symbol: 'PPARG & KCNJ11',
        name: 'Insulin Sensitivity & Potassium Channel Subunits',
        clinicalSignificance: 'Modulates peripheral insulin resistance and neonatal/atypical diabetes pathogenesis.',
        actionableImpact: 'Directs personalized selection of GLP-1, SGLT-2, or oral hypoglycemic medication classes.',
      },
    ],
    clinicalIndications: [
      'Diabetes diagnosed at a younger age (<35 years) with normal body mass index (BMI).',
      'Diabetes spanning three consecutive generations in the family lineage.',
      'Absence of typical Type 2 diabetes characteristics (no obesity, normal lipid profile).',
      'Negative pancreatic islet autoantibodies (ruling out classic Type 1 diabetes).',
      'Mild, persistent fasting elevated blood sugar that remains stable over decades.',
    ],
    medicareCoverageCriteria: 'Physician-ordered metabolic genetic analysis sequences 16 pancreatic biomarkers to differentiate Monogenic Diabetes (MODY) from Type 2 diabetes and guide tailored therapy.',
    sampleReportSummary: {
      resultStatus: 'Pathogenic Variant Identified',
      keyFinding: 'Heterozygous pathogenic mutation identified in HNF1A (c.872dupC, p.Pro291fs) confirming MODY 3.',
      clinicalRecommendation: 'Discuss with endocrinologist for potential transition from insulin therapy to oral low-dose glimepiride/gliclazide with continuous glucose monitoring.',
    },
    keyStats: [
      { label: 'Metabolic Genes', value: '16 Biomarkers' },
      { label: 'Diagnostic Impact', value: 'Medication Shift' },
      { label: 'Turnaround Time', value: '7–10 Days' },
      { label: 'Accuracy', value: '99.9%' },
    ],
  },
  {
    id: 'prog-thyroid',
    slug: 'thyroid-endocrine',
    name: 'Thyroid & Endocrine Health Panel',
    clinicalCode: 'PANEL-THY-14',
    category: 'endocrine',
    heroBadge: 'Endocrine Health • Nodule & Autoimmune Analysis',
    shortDescription: 'Evaluates hereditary markers for medullary thyroid carcinoma, multiple endocrine neoplasia (MEN), and autoimmune thyroiditis.',
    fullOverview: 'The Thyroid and Endocrine Panel provides vital genetic insights into both neoplastic risks (such as familial Medullary Thyroid Carcinoma) and inherited autoimmune pathways underlying Hashimoto’s disease and Graves’ ophthalmopathy. Accurate profiling empowers physicians to personalize surveillance and hormone balance protocols.',
    iconName: 'Layers',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'RET',
        name: 'Proto-Oncogene Tyrosine Kinase Receptor',
        clinicalSignificance: 'The definitive genetic driver of Multiple Endocrine Neoplasia Type 2 (MEN2) and familial Medullary Thyroid Cancer.',
        actionableImpact: 'Guides life-saving prophylactic surgical timing, calcitonin monitoring, and targeted RET kinase inhibitor therapy.',
      },
      {
        symbol: 'MEN1',
        name: 'Menin Tumor Suppressor',
        clinicalSignificance: 'Regulates parathyroid, anterior pituitary, and pancreatic neuroendocrine cell proliferation.',
        actionableImpact: 'Directs annual calcium/PTH blood testing and specialized endocrine MRI surveillance.',
      },
      {
        symbol: 'TSHR & TG',
        name: 'Thyrotropin Receptor & Thyroglobulin',
        clinicalSignificance: 'Governs thyroid hormone synthesis, congenital dyshormonogenesis, and autoimmune receptor reactivity.',
        actionableImpact: 'Assists endocrinologists in fine-tuning synthetic levothyroxine / T3 combination dosing protocols.',
      },
    ],
    clinicalIndications: [
      'Personal diagnosis or family history of medullary thyroid cancer or pheochromocytoma.',
      'Unexplained elevated serum calcitonin or parathyroid hormone (PTH) levels.',
      'Multiple family members with refractory thyroid nodules, goiter, or autoimmune thyroid disorders.',
      'Clinical signs of Multiple Endocrine Neoplasia (hypercalcemia, pituitary tumors).',
    ],
    medicareCoverageCriteria: 'Physician-ordered endocrine genomic profiling analyzes RET, MEN1, and hormone synthesis loci to evaluate thyroid nodule risks, hereditary neoplasms, and autoimmune pathways.',
    sampleReportSummary: {
      resultStatus: 'Negative / Standard Baseline',
      keyFinding: 'No pathogenic variants detected in RET, MEN1, or primary endocrine malignancy loci.',
      clinicalRecommendation: 'Routine annual TSH/Free T4 monitoring with primary care physician; standard thyroid ultrasound management as clinically indicated.',
    },
    keyStats: [
      { label: 'Endocrine Genes', value: '14 Targets' },
      { label: 'Medicare Part B', value: '100% Covered' },
      { label: 'Turnaround', value: '7–10 Days' },
      { label: 'Sample', value: 'Buccal Swab' },
    ],
  },
  {
    id: 'prog-ophthalmic',
    slug: 'ophthalmic',
    name: 'Inherited Ophthalmic & Vision Health',
    clinicalCode: 'PANEL-OPH-20',
    category: 'ophthalmic',
    heroBadge: 'Preserve Vision • Macular & Glaucoma Genetics',
    shortDescription: 'Identifies genetic factors tied to progressive vision loss, early macular degeneration, early-onset glaucoma, and retinal dystrophies.',
    fullOverview: 'Many degenerative eye diseases progress silently before irreversible optic nerve or retinal damage occurs. This panel investigates genetic variants associated with age-related macular degeneration (AMD), juvenile and open-angle glaucoma, and inherited retinal dystrophies—enabling ophthalmologists to implement early vision-saving interventions and targeted antioxidant therapies.',
    iconName: 'Eye',
    sampleTurnaround: '7–10 Business Days',
    specimenType: 'Non-invasive Buccal Cheek Swab',
    genesAnalyzed: [
      {
        symbol: 'ABCA4 & BEST1',
        name: 'Retinal ATP-Binding Cassette Transporters',
        clinicalSignificance: 'Primary loci for Stargardt disease, vitelliform macular dystrophy, and inherited maculopathies.',
        actionableImpact: 'Directs strict blue-light/UV protection, AREDS2 nutritional adjustments, and micro-perimetry tracking.',
      },
      {
        symbol: 'MYOC & OPTN',
        name: 'Myocilin & Optineurin Trabecular Regulators',
        clinicalSignificance: 'Associated with early-onset primary open-angle glaucoma and normal-tension glaucoma.',
        actionableImpact: 'Guides proactive intraocular pressure (IOP) reduction protocols before visual field constriction occurs.',
      },
      {
        symbol: 'RPGR & RHO',
        name: 'Retinitis Pigmentosa GTPase & Rhodopsin Photoreceptors',
        clinicalSignificance: 'Critical for rod and cone photoreceptor maintenance and dark adaptation.',
        actionableImpact: 'Qualifies eligible patients for emerging gene therapy protocols and specialized low-vision rehabilitation.',
      },
    ],
    clinicalIndications: [
      'Early onset of macular degeneration symptoms before age 60.',
      'Immediate family member diagnosed with glaucoma at a young age (<50 years).',
      'Unexplained progressive loss of night vision or peripheral visual fields.',
      'Family history of inherited retinal dystrophy or Stargardt disease.',
    ],
    medicareCoverageCriteria: 'Physician-ordered ophthalmic genomic testing analyzes 20 retinal and trabecular biomarkers to detect early genetic risks for macular degeneration, glaucoma, and inherited vision loss.',
    sampleReportSummary: {
      resultStatus: 'Moderate Risk Factor',
      keyFinding: 'High-risk susceptibility alleles detected in complement factor H (CFH) and ARMS2 macular risk loci.',
      clinicalRecommendation: 'Recommend semi-annual dilated retinal exams, Amsler grid self-monitoring, and initiating AREDS 2 formula antioxidant supplementation.',
    },
    keyStats: [
      { label: 'Ophthalmic Genes', value: '20 Targets' },
      { label: 'Turnaround Time', value: '7–10 Days' },
      { label: 'Collection', value: 'Cheek Swab' },
      { label: 'Lab Certified', value: 'CLIA & CAP' },
    ],
  },
];
