/**
 * Verbatim consent statements displayed across patient forms.
 */
export const CONSENT_STATEMENTS = {
  /**
   * Express Written Consent used on Genetic Testing, DME, and Medical Alert forms.
   */
  EXPRESS_WRITTEN_CONSENT:
    'By submitting, you are giving Express Written Consent authorizing the Wellness Eligibility Program team to contact you via voice, SMS, or email at the information provided regarding the following: confirming personal information, order submission or updates, and other healthcare benefits. The patient understands that these calls or messages may be generated by an automated dialer or messaging system. The patient is not required to provide consent as a condition of requesting or receiving any products or services. The patient also understands that this offer does not qualify them for any prize or reward. You understand that you can opt out at any time by replying STOP to the messages.',

  /**
   * Automated SMS updates consent in Multi-Step Wizard.
   */
  SMS_TRACKING_CONSENT:
    'I consent to receive automated SMS updates regarding my swab kit dispatch, lab receipt, and physician review schedule.',

  /**
   * Caregiver / guardian consent in Multi-Step Wizard.
   */
  CAREGIVER_CONSENT:
    'I am a family caregiver or legal guardian completing this request on behalf of the patient.',
} as const;

/**
 * Formats boolean consent into clear affirmative status string.
 */
export function formatConsentStatus(consentGiven: boolean): string {
  return consentGiven ? 'I Agree' : 'No';
}
