'use client';

import React, { useState } from 'react';
import {
  FileSpreadsheet,
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  Download,
  Dna,
  Pill,
  ArrowRight,
  Info,
} from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';

export default function SampleReportsPage() {
  const [activeTab, setActiveTab] = useState<'cgx' | 'pgx'>('pgx');

  return (
    <div className="min-h-screen bg-[#FDFCF7] py-12 lg:py-20">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        {/* Header */}
        <div className="text-center space-y-3 max-w-3xl mx-auto">
          <Badge variant="teal" size="md">
            Clinical Transparency
          </Badge>
          <h1 className="font-serif-heading font-bold text-3xl sm:text-5xl text-[#0D1B2A] tracking-tight">
            Interactive Genetic Report Explorer
          </h1>
          <p className="font-sans-body text-sm sm:text-base text-slate-600">
            Explore sample diagnostic reports generated by our CLIA-certified partner laboratories, complete with clinical summaries and actionable physician guidance.
          </p>
        </div>

        {/* Tab Switcher */}
        <div className="flex justify-center">
          <div className="p-1.5 rounded-full bg-slate-200/80 inline-flex items-center gap-2">
            <button
              onClick={() => setActiveTab('pgx')}
              className={`px-6 py-2.5 rounded-full text-xs sm:text-sm font-bold transition-all cursor-pointer ${
                activeTab === 'pgx'
                  ? 'bg-[#0D1B2A] text-white shadow-xs'
                  : 'text-slate-700 hover:text-[#0D1B2A]'
              }`}
            >
              Pharmacogenomics Report (PGx)
            </button>
            <button
              onClick={() => setActiveTab('cgx')}
              className={`px-6 py-2.5 rounded-full text-xs sm:text-sm font-bold transition-all cursor-pointer ${
                activeTab === 'cgx'
                  ? 'bg-[#0D1B2A] text-white shadow-xs'
                  : 'text-slate-700 hover:text-[#0D1B2A]'
              }`}
            >
              Hereditary Cancer Report (CGx)
            </button>
          </div>
        </div>

        {/* PGx Interactive Report View */}
        {activeTab === 'pgx' && (
          <Card className="p-6 sm:p-10 rounded-3xl bg-white border border-slate-200/90 shadow-2xl space-y-8 animate-fade-in">
            {/* Header Strip of Report */}
            <div className="p-6 rounded-2xl bg-[#FDFCF7] border border-slate-200 text-[#0D1B2A] flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div>
                <span className="text-xs font-mono font-bold text-[#0D9488] uppercase tracking-widest block">
                  CLIA # 45D2109841 • CAP ACCREDITED
                </span>
                <h3 className="font-serif-heading font-bold text-xl text-[#0D1B2A] mt-1">
                  Pharmacogenomic (PGx) Precision Medication Profile
                </h3>
                <p className="text-xs text-slate-500">
                  Patient: Harold M. • Age: 68 • Ordered by: Dr. Robert Vance, MD
                </p>
              </div>
              <Badge variant="emerald" size="sm">
                Clinical Complete
              </Badge>
            </div>

            {/* Traffic Light Drug Response Legend */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 flex items-start gap-3">
                <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-xs text-emerald-900">Standard Therapeutic Response</h4>
                  <p className="text-[11px] text-emerald-700 mt-0.5">Normal rate of metabolism. Use medication as typically directed.</p>
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-xs text-amber-900">Use with Caution / Monitor Dosage</h4>
                  <p className="text-[11px] text-amber-700 mt-0.5">Moderate gene-drug alteration. Physician may adjust baseline dosage.</p>
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-rose-50 border border-rose-200 flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-rose-600 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-bold text-xs text-rose-900">High Risk / Consider Alternative</h4>
                  <p className="text-[11px] text-rose-700 mt-0.5">Severe toxicity or non-response risk. Alternative medication advised.</p>
                </div>
              </div>
            </div>

            {/* Medication Evaluation Table */}
            <div className="overflow-x-auto rounded-2xl border border-slate-200">
              <table className="w-full text-left border-collapse text-xs sm:text-sm">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200 text-slate-700 uppercase font-bold text-[11px]">
                    <th className="p-4">Prescription Medication</th>
                    <th className="p-4">Primary Indication</th>
                    <th className="p-4">Associated Enzyme</th>
                    <th className="p-4">Metabolic Phenotype</th>
                    <th className="p-4">Actionable Clinical Recommendation</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  <tr className="bg-rose-50/30">
                    <td className="p-4 font-bold text-slate-900">Clopidogrel (Plavix)</td>
                    <td className="p-4 text-slate-600">Cardiovascular / Antiplatelet</td>
                    <td className="p-4 font-mono font-bold text-[#0D1B2A]">CYP2C19</td>
                    <td className="p-4">
                      <span className="font-bold text-xs text-rose-700 bg-rose-100 px-2 py-0.5 rounded-full">
                        Intermediate Metabolizer (*1/*2)
                      </span>
                    </td>
                    <td className="p-4 text-slate-700 text-xs leading-relaxed">
                      Reduced bioactivation. Patient at increased risk for ischemic events. <strong>Consider alternative antiplatelet (e.g. Prasugrel or Ticagrelor).</strong>
                    </td>
                  </tr>

                  <tr className="bg-amber-50/30">
                    <td className="p-4 font-bold text-slate-900">Simvastatin (Zocor)</td>
                    <td className="p-4 text-slate-600">Hypercholesterolemia</td>
                    <td className="p-4 font-mono font-bold text-[#0D1B2A]">SLCO1B1</td>
                    <td className="p-4">
                      <span className="font-bold text-xs text-amber-700 bg-amber-100 px-2 py-0.5 rounded-full">
                        Decreased Function (*5)
                      </span>
                    </td>
                    <td className="p-4 text-slate-700 text-xs leading-relaxed">
                      Elevated systemic statin exposure. High risk of myopathy (muscle breakdown). <strong>Cap dose at 20mg or switch to Rosuvastatin.</strong>
                    </td>
                  </tr>

                  <tr className="bg-emerald-50/30">
                    <td className="p-4 font-bold text-slate-900">Metoprolol (Lopressor)</td>
                    <td className="p-4 text-slate-600">Hypertension / Beta-Blocker</td>
                    <td className="p-4 font-mono font-bold text-[#0D1B2A]">CYP2D6</td>
                    <td className="p-4">
                      <span className="font-bold text-xs text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded-full">
                        Normal Metabolizer (*1/*1)
                      </span>
                    </td>
                    <td className="p-4 text-slate-700 text-xs leading-relaxed">
                      Standard clearance rate observed. <strong>Initiate and titrate per standard clinical guidelines.</strong>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </Card>
        )}

        {/* CGx Interactive Report View */}
        {activeTab === 'cgx' && (
          <Card className="p-6 sm:p-10 rounded-3xl bg-white border border-slate-200/90 shadow-2xl space-y-8 animate-fade-in">
            <div className="p-6 rounded-2xl bg-[#FDFCF7] border border-slate-200 text-[#0D1B2A] flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div>
                <span className="text-xs font-mono font-bold text-[#0D9488] uppercase tracking-widest block">
                  CLIA # 45D2109841 • 32 GENES EVALUATED
                </span>
                <h3 className="font-serif-heading font-bold text-xl text-[#0D1B2A] mt-1">
                  Hereditary Cancer Susceptibility Comprehensive Panel (CGx)
                </h3>
                <p className="text-xs text-slate-500">
                  Patient: Sarah J. • Age: 44 • Specimen: Buccal Swab NGS
                </p>
              </div>
              <Badge variant="rose" size="sm">
                Positive for Actionable Variant
              </Badge>
            </div>

            <div className="p-6 rounded-2xl bg-rose-50/60 border border-rose-200 space-y-3">
              <div className="flex items-center gap-2 text-rose-800 font-bold text-sm">
                <AlertTriangle className="w-5 h-5 text-rose-600 shrink-0" />
                <span>Pathogenic Heterozygous Mutation Identified in BRCA2</span>
              </div>
              <p className="text-xs sm:text-sm text-slate-700 leading-relaxed">
                Variant: <strong>c.5946delT (p.Ser1982fs)</strong>. This frameshift deletion disrupts the C-terminal domain of the BRCA2 tumor-suppressor protein, conferring elevated lifetime risk for hereditary breast, ovarian, and pancreatic neoplasms.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-serif-heading font-bold text-base text-[#0D1B2A]">
                NCCN-Aligned Clinical Action Plan for Primary Care Provider:
              </h4>
              <ul className="space-y-2 text-xs sm:text-sm text-slate-700 list-disc list-inside leading-relaxed">
                <li>Refer to certified genetic counselor (CGC) for formal post-test counseling and family cascade testing review.</li>
                <li>Initiate annual contrast-enhanced breast MRI alternating with high-resolution digital mammography starting immediately.</li>
                <li>Discuss individualized risk-reducing strategies and prophylactic surgical considerations with gynecologic oncologist.</li>
                <li>Annual pancreatic cancer surveillance protocol (EUS / MRCP) recommended beginning at age 50.</li>
              </ul>
            </div>
          </Card>
        )}

        {/* CTA */}
        <div className="text-center">
          <Button
            href="/eligibility-checker"
            size="lg"
            variant="primary"
            className="shadow-md shadow-teal-700/20 font-semibold rounded-full"
            icon={<ArrowRight className="w-4 h-4" />}
          >
            Check If You Qualify for At-Home Testing &rarr;
          </Button>
        </div>
      </div>
    </div>
  );
}
